#!/bin/bash

# SuperTail 快速演示脚本

clear

echo "╔════════════════════════════════════════════════╗"
echo "║                                                ║"
echo "║         SuperTail - 智能日志监控工具          ║"
echo "║                                                ║"
echo "║        AI-Powered Log Monitoring Tool          ║"
echo "║                                                ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "👋 欢迎使用 SuperTail！"
echo ""
echo "本演示将展示 SuperTail 的核心功能："
echo "  • 批处理模式"
echo "  • 智能过滤"
echo "  • 上下文显示"
echo "  • 系统通知"
echo ""
read -p "按 Enter 开始演示..." 

clear

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "演示 1: 批处理模式 - 智能累积多行日志"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "传统方式："
echo "  ❌ 每行单独分析 → 慢"
echo "  ❌ 每行单独通知 → 烦"
echo "  ❌ Token 消耗大 → 贵"
echo ""
echo "SuperTail 批处理："
echo "  ✅ 累积 10 行批量分析 → 快"
echo "  ✅ 一批只通知 1 次 → 爽"  
echo "  ✅ 节省 70-90% Token → 省"
echo ""
read -p "按 Enter 查看效果..."

./tests/quick-batch-test.sh

echo ""
read -p "按 Enter 继续下一个演示..."

clear

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "演示 2: 上下文显示 - 完整的错误场景"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "传统方式："
echo "  ❌ 只看到一行错误"
echo "  ❌ 不知道什么操作导致的"
echo "  ❌ 异常堆栈被拆分"
echo ""
echo "SuperTail 上下文："
echo "  ✅ 自动显示前后 3 行"
echo "  ✅ 完整的错误场景"
echo "  ✅ 异常堆栈自动合并"
echo ""
read -p "按 Enter 查看效果..."

./tests/test-context.sh

echo ""
read -p "按 Enter 继续下一个演示..."

clear

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "演示 3: 简洁输出 - 聚焦问题"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "传统方式："
echo "  ❌ DEBUG、INFO 刷屏"
echo "  ❌ 重要日志被淹没"
echo ""
echo "SuperTail 简洁输出："
echo "  ✅ 默认只显示重要日志"
echo "  ✅ INFO/DEBUG 自动过滤"
echo "  ✅ 输出清爽，聚焦问题"
echo ""
read -p "按 Enter 查看效果..."

./tests/test-clean-output.sh

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 演示完成！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 SuperTail 的核心优势："
echo ""
echo "1. 📦 批处理模式"
echo "   • 节省 70-90% Token"
echo "   • 减少 80-90% 通知"
echo "   • 提高 10 倍速度"
echo ""
echo "2. ⚡ 本地预过滤"
echo "   • DEBUG/INFO 不调用 AI"
echo "   • 处理速度 < 0.1秒"
echo "   • 节省 60-80% API 调用"
echo ""
echo "3. 📋 上下文显示"
echo "   • 重要日志前后 3 行"
echo "   • 完整的错误场景"
echo "   • 方便排查问题"
echo ""
echo "4. 🎯 简洁输出"
echo "   • 只显示重要日志"
echo "   • 聚焦问题"
echo "   • 不被噪音干扰"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 开始使用："
echo ""
echo "  # 监控日志"
echo "  ./supertail -f /var/log/app.log --format java"
echo ""
echo "  # 查看帮助"
echo "  ./supertail --help"
echo ""
echo "  # 阅读文档"
echo "  cat README.md"
echo "  cat QUICK_START.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⭐ 如果喜欢这个项目，请在 GitHub 上给一个 Star！"
echo ""
echo "Happy logging! 🎊"
echo ""

