version: '3.8'

services:
  aipipe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_TIME: ${BUILD_TIME:-$(date -u +%Y-%m-%d_%H:%M:%S)}
        GIT_COMMIT: ${GIT_COMMIT:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}
    image: aipipe:${VERSION:-dev}
    container_name: aipipe
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      # 挂载日志目录
      - /var/log:/var/log:ro
      # 挂载配置目录
      - ./config:/app/config:ro
      # 挂载 Docker socket (如果需要监控 Docker 日志)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aipipe-network
    # 示例：监控系统日志
    command: ["-f", "/var/log/syslog", "--format", "syslog", "--verbose"]
    # 如果需要监控多个日志文件，可以使用多个容器实例
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

  # 示例：监控 Docker 容器日志
  aipipe-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: aipipe:${VERSION:-dev}
    container_name: aipipe-docker
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config:ro
    networks:
      - aipipe-network
    # 监控 Docker 日志
    command: ["docker", "logs", "-f", "nginx", "--format", "docker", "--verbose"]
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  # 示例：监控 Nginx 日志
  nginx:
    image: nginx:alpine
    container_name: nginx-example
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./examples/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./examples/html:/usr/share/nginx/html:ro
    networks:
      - aipipe-network

  # 示例：监控应用日志
  aipipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aipipe:${VERSION:-dev}
    container_name: aipipe-app
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./examples/app.log:/var/log/app.log:ro
      - ./config:/app/config:ro
    networks:
      - aipipe-network
    # 监控应用日志
    command: ["-f", "/var/log/app.log", "--format", "java", "--verbose", "--batch-size", "10"]

networks:
  aipipe-network:
    driver: bridge

volumes:
  config:
    driver: local
