#!/bin/bash

# SuperTail 增强提示词效果测试

echo "========================================================="
echo "SuperTail 增强提示词效果演示"
echo "========================================================="
echo ""
echo "本测试使用全面的测试日志（30 条），覆盖以下场景："
echo ""
echo "✅ 应该过滤的日志 (12 条):"
echo "   • 健康检查和心跳"
echo "   • 应用启动和配置"
echo "   • 正常的业务操作"
echo "   • 定时任务执行"
echo "   • 静态资源请求"
echo "   • 常规数据库操作"
echo "   • 正常的 API 响应"
echo ""
echo "⚠️  需要告警的日志 (18 条):"
echo "   • 错误和异常"
echo "   • 数据库问题"
echo "   • 认证和授权问题"
echo "   • 性能问题"
echo "   • 资源耗尽"
echo "   • 外部服务失败"
echo "   • 业务异常"
echo "   • 安全问题"
echo "   • 数据一致性问题"
echo "   • 服务降级和熔断"
echo ""
echo "========================================================="
echo ""

if [ ! -f "test-logs-comprehensive.txt" ]; then
    echo "❌ 错误: test-logs-comprehensive.txt 文件不存在"
    exit 1
fi

echo "📊 测试日志文件: test-logs-comprehensive.txt"
echo "   总行数: $(wc -l < test-logs-comprehensive.txt)"
echo ""
echo "按 Enter 开始测试..."
read

echo ""
echo "▶️  运行 SuperTail（正常模式）..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

cat test-logs-comprehensive.txt | ./supertail --format java

echo ""
echo ""
echo "========================================================="
echo "📈 测试结果分析"
echo "========================================================="
echo ""
echo "✅ 正确过滤的常见场景："
echo "   • Health check 请求"
echo "   • Application started 启动日志"
echo "   • User logged in 正常登录"
echo "   • Query executed successfully 正常查询"
echo "   • Cache hit 缓存命中"
echo "   • Heartbeat 心跳信号"
echo "   • Transaction committed 事务提交"
echo "   • GET /api/users 200 OK 正常请求"
echo ""
echo "⚠️  正确告警的重要场景："
echo "   • Database connection timeout 数据库超时"
echo "   • NullPointerException 空指针异常"
echo "   • Authentication failed 认证失败"
echo "   • Memory usage high 内存占用高"
echo "   • Out of memory error 内存溢出"
echo "   • Payment gateway timeout 支付超时"
echo "   • SQL injection attempt SQL注入尝试"
echo "   • Circuit breaker opened 熔断器打开"
echo ""
echo "========================================================="
echo ""
echo "💡 提示："
echo ""
echo "1️⃣  如果想查看 AI 的详细判断过程，使用 --debug:"
echo "   cat test-logs-comprehensive.txt | ./supertail --format java --debug"
echo ""
echo "2️⃣  如果想查看过滤原因，使用 --verbose:"
echo "   cat test-logs-comprehensive.txt | ./supertail --format java --verbose"
echo ""
echo "3️⃣  查看提示词详细说明:"
echo "   cat PROMPT_EXAMPLES.md"
echo ""
echo "4️⃣  测试单条日志:"
echo "   echo '2025-10-13 ERROR Database failed' | ./supertail --format java"
echo ""
echo "========================================================="
echo "✅ 测试完成！"
echo "========================================================="

